name: HugoBuild
on:
  push:
    Branches:
      - hugo-source

jobs:
  deploy:
    if: ${{ github.repository == 'atsign-foundation/atsign.dev' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive  # To get theme
          fetch-depth: 0

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.83.1"
          extended: true  # MemE theme needs Hugo Extended

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          cname: devstaging.atsign.wtf
